# Once edited, rename this file to docker-compose.yml

version: '3'
services:
  redis:
    image: redis:alpine
    ports:
    - 6379:6379
  postgres:
    image: postgres:alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: dero_merchant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_here
    volumes:
    - ./postgres/data:/var/lib/postgresql/data
